"use client";
import {
  DIE_CONTAINER_IMAGES,
  SIZE_IMAGES as LOCAL_SIZE_IMAGES,
  TYPE_IMAGES as LOCAL_TYPE_IMAGES,
} from "@/lib/imageAssets";

// Static product data for initial display - will be synced with entity
export const PRODUCT_DATA = [
  {
    id: "p1",
    title: "20 Fuß High Cube Seecontainer",
    slug: "20ft-high-cube-seecontainer",
    short_description: "Ideal für Lagerung und Transport mit zusätzlicher Höhe.",
    price_from: 2490,
    size: "20ft",
    condition: "Neu",
    container_type: "High Cube",
    color: "Anthrazit",
    badge: "Bestseller",
    is_available: true,
    is_featured: true,
    image_url: DIE_CONTAINER_IMAGES.newShippingContainers,
    gallery_urls: [
      DIE_CONTAINER_IMAGES.yard,
      DIE_CONTAINER_IMAGES.shippingLogistics,
      DIE_CONTAINER_IMAGES.usedSeecontainers,
      DIE_CONTAINER_IMAGES.crane,
    ],
    outer_length: "6.058 mm",
    outer_width: "2.438 mm",
    outer_height: "2.896 mm",
    weight: "2.350 kg",
    payload: "28.130 kg",
    material: "Corten-Stahl",
    floor: "Marineboden 28mm",
    doors: "Doppelflügeltüren mit Verriegelung",
    csc_certified: true,
    weather_resistant: true,
    description: "Der 20 Fuß High Cube Seecontainer bietet mit einer Höhe von 2.896 mm deutlich mehr Stauraum als ein Standard-Container. Perfekt für sperrige Güter, als Werkstatt oder Lagerfläche. CSC-zertifiziert und für den weltweiten Transport geeignet."
  },
  {
    id: "p2",
    title: "40 Fuß Standardcontainer",
    slug: "40ft-standardcontainer",
    short_description: "Maximaler Stauraum für große Projekte.",
    price_from: 3290,
    size: "40ft",
    condition: "Gebraucht",
    container_type: "Standard",
    color: "Blau",
    badge: "Gebraucht",
    is_available: true,
    is_featured: true,
    image_url: DIE_CONTAINER_IMAGES.usedSeecontainers,
    gallery_urls: [
      DIE_CONTAINER_IMAGES.yard,
      DIE_CONTAINER_IMAGES.newShippingContainers,
      DIE_CONTAINER_IMAGES.shippingLogistics,
      DIE_CONTAINER_IMAGES.crane,
    ],
    outer_length: "12.192 mm",
    outer_width: "2.438 mm",
    outer_height: "2.591 mm",
    weight: "3.800 kg",
    payload: "26.680 kg",
    material: "Corten-Stahl",
    floor: "Marineboden 28mm",
    doors: "Doppelflügeltüren mit Verriegelung",
    csc_certified: true,
    weather_resistant: true,
    description: "Der 40 Fuß Standardcontainer bietet mit ca. 67 m³ Ladevolumen den maximalen Stauraum. Ideal für große Lagerprojekte, Baustellen oder als Basis für Umbauten."
  },
  {
    id: "p3",
    title: "10 Fuß Lagercontainer",
    slug: "10ft-lagercontainer",
    short_description: "Kompakt und vielseitig einsetzbar.",
    price_from: 1690,
    size: "10ft",
    condition: "Neu",
    container_type: "Standard",
    color: "Grün",
    badge: "Neu",
    is_available: true,
    is_featured: true,
    image_url: DIE_CONTAINER_IMAGES.yard,
    gallery_urls: [
      DIE_CONTAINER_IMAGES.newShippingContainers,
      DIE_CONTAINER_IMAGES.usedSeecontainers,
      DIE_CONTAINER_IMAGES.shippingLogistics,
    ],
    outer_length: "2.991 mm",
    outer_width: "2.438 mm",
    outer_height: "2.591 mm",
    weight: "1.300 kg",
    payload: "10.200 kg",
    material: "Corten-Stahl",
    floor: "Marineboden 28mm",
    doors: "Doppelflügeltüren mit Verriegelung",
    csc_certified: true,
    weather_resistant: true,
    description: "Der 10 Fuß Lagercontainer ist die perfekte Lösung für kompakte Lagerbedürfnisse. Platzsparend und dennoch robust – ideal für Gärten, Baustellen oder als Ergänzung zu bestehenden Lagerflächen."
  },
  {
    id: "p4",
    title: "20 Fuß Standardcontainer",
    slug: "20ft-standardcontainer",
    short_description: "Der Klassiker für Lagerung und Transport.",
    price_from: 1990,
    size: "20ft",
    condition: "Gebraucht",
    container_type: "Standard",
    color: "Blau",
    badge: "Gebraucht",
    is_available: true,
    is_featured: true,
    image_url: DIE_CONTAINER_IMAGES.usedSeecontainers,
    gallery_urls: [
      DIE_CONTAINER_IMAGES.newShippingContainers,
      DIE_CONTAINER_IMAGES.shippingLogistics,
      DIE_CONTAINER_IMAGES.yard,
      DIE_CONTAINER_IMAGES.crane,
    ],
    outer_length: "6.058 mm",
    outer_width: "2.438 mm",
    outer_height: "2.591 mm",
    weight: "2.230 kg",
    payload: "21.770 kg",
    material: "Corten-Stahl",
    floor: "Marineboden 28mm",
    doors: "Doppelflügeltüren mit Verriegelung",
    csc_certified: true,
    weather_resistant: true,
    description: "Der 20 Fuß Standardcontainer ist der meistgenutzte Container weltweit. Robust, vielseitig und zu einem attraktiven Preis – ideal als Lager, Werkstatt oder für den Transport."
  },
  {
    id: "p5",
    title: "40 Fuß High Cube Container",
    slug: "40ft-high-cube-container",
    short_description: "Maximale Kapazität mit extra Höhe.",
    price_from: 4190,
    size: "40ft",
    condition: "Neu",
    container_type: "High Cube",
    color: "Anthrazit",
    badge: "Neu",
    is_available: true,
    is_featured: true,
    image_url: DIE_CONTAINER_IMAGES.yard,
    gallery_urls: [
      DIE_CONTAINER_IMAGES.newShippingContainers,
      DIE_CONTAINER_IMAGES.usedSeecontainers,
      DIE_CONTAINER_IMAGES.shippingLogistics,
      DIE_CONTAINER_IMAGES.crane,
    ],
    outer_length: "12.192 mm",
    outer_width: "2.438 mm",
    outer_height: "2.896 mm",
    weight: "3.900 kg",
    payload: "26.580 kg",
    material: "Corten-Stahl",
    floor: "Marineboden 28mm",
    doors: "Doppelflügeltüren mit Verriegelung",
    csc_certified: true,
    weather_resistant: true,
    description: "Der 40 Fuß High Cube vereint maximalen Stauraum mit zusätzlicher Höhe. Perfekt für voluminöse Güter, Fahrzeuge oder als Basis für hochwertige Containerumbauten."
  },
  {
    id: "p6",
    title: "20 Fuß Open Side Container",
    slug: "20ft-open-side-container",
    short_description: "Seitliche Öffnung für einfaches Be- und Entladen.",
    price_from: 3490,
    size: "20ft",
    condition: "Neu",
    container_type: "Open Side",
    color: "Blau",
    badge: "Neu",
    is_available: true,
    is_featured: true,
    image_url: DIE_CONTAINER_IMAGES.newShippingContainers,
    gallery_urls: [
      DIE_CONTAINER_IMAGES.shippingLogistics,
      DIE_CONTAINER_IMAGES.yard,
      DIE_CONTAINER_IMAGES.usedSeecontainers,
    ],
    outer_length: "6.058 mm",
    outer_width: "2.438 mm",
    outer_height: "2.591 mm",
    weight: "2.450 kg",
    payload: "21.550 kg",
    material: "Corten-Stahl",
    floor: "Marineboden 28mm",
    doors: "Seitliche Flügeltüren + Stirnseitige Doppeltüren",
    csc_certified: true,
    weather_resistant: true,
    description: "Der Open Side Container bietet durch die vollständig zu öffnende Seitenwand maximale Flexibilität beim Be- und Entladen. Ideal für sperrige Güter oder den Einsatz als mobiler Verkaufsraum."
  },
  {
    id: "p7",
    title: "20 Fuß Kühlcontainer",
    slug: "20ft-kuehlcontainer",
    short_description: "Temperaturgeführte Lagerung und Transport.",
    price_from: 5990,
    size: "20ft",
    condition: "Generalüberholt",
    container_type: "Kühlcontainer",
    color: "Weiß",
    badge: "Angebot",
    is_available: true,
    is_featured: true,
    image_url: DIE_CONTAINER_IMAGES.shippingLogistics,
    gallery_urls: [
      DIE_CONTAINER_IMAGES.yard,
      DIE_CONTAINER_IMAGES.newShippingContainers,
      DIE_CONTAINER_IMAGES.usedSeecontainers,
    ],
    outer_length: "6.058 mm",
    outer_width: "2.438 mm",
    outer_height: "2.591 mm",
    weight: "3.100 kg",
    payload: "20.900 kg",
    material: "Edelstahl-Innenverkleidung",
    floor: "T-Profil Aluminium",
    doors: "Isolierte Doppelflügeltüren",
    csc_certified: true,
    weather_resistant: true,
    description: "Der Kühlcontainer ermöglicht temperaturgeführte Lagerung von -25°C bis +25°C. Ideal für Lebensmittel, Pharmazeutika oder andere temperaturempfindliche Güter."
  },
  {
    id: "p8",
    title: "20 Fuß Bürocontainer",
    slug: "20ft-buerocontainer",
    short_description: "Sofort bezugsfertiges mobiles Büro.",
    price_from: 7490,
    size: "20ft",
    condition: "Neu",
    container_type: "Bürocontainer",
    color: "Anthrazit",
    badge: "Bestseller",
    is_available: true,
    is_featured: true,
    image_url: DIE_CONTAINER_IMAGES.mobileWohncontainer,
    gallery_urls: [
      DIE_CONTAINER_IMAGES.wohncontainerTransport,
      DIE_CONTAINER_IMAGES.yard,
      DIE_CONTAINER_IMAGES.shippingLogistics,
      DIE_CONTAINER_IMAGES.wohncontainers,
    ],
    outer_length: "6.058 mm",
    outer_width: "2.438 mm",
    outer_height: "2.591 mm",
    weight: "2.800 kg",
    payload: "21.200 kg",
    material: "Corten-Stahl mit Isolierung",
    floor: "PVC auf Isolierung",
    doors: "Eingangstür mit Sicherheitsschloss",
    csc_certified: false,
    weather_resistant: true,
    description: "Der Bürocontainer bietet ein sofort bezugsfertiges Büro mit Elektroinstallation, Beleuchtung, Fenster und Isolierung. Ideal als Baustellenbüro, temporärer Arbeitsplatz oder Showroom."
  }
];

export const SIZE_IMAGES = LOCAL_SIZE_IMAGES;
export const TYPE_IMAGES = LOCAL_TYPE_IMAGES;

export const HERO_IMAGE = DIE_CONTAINER_IMAGES.newShippingContainers;
export const DELIVERY_IMAGE = DIE_CONTAINER_IMAGES.shippingLogistics;
